config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  post "languages/set_language", to: "languages#set_language"
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :booking_carts
  resources :users
  get "update_info_user", to: "booking_carts#update_info_user"
  post "order", to: "booking_carts#order"
  resources :orders, only: [:index, :new, :create, :update] do
    resources :order_details, only: [:index]
  end
  resources :order_details, only: [:update]
  resources :statisticals, only: [:create]
  
  namespace :admin do
    root "statisticals#index"
    resources :statisticals, only: [:index]
    resources :users
    resources :products
    resources :orders, only: [:index, :update] do
      resources :order_details, only: [:index]
    end
    get "report", to: "order_details#report"
    resources :order_details, only: [:index, :report]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true

  scope :infor_comment, ->{select :id, :user_id, :product_id, :parent_id, :content, :created_at}
  scope :created_desc, ->{order created_at: :asc}
  scope :without_parent, ->{where parent_id: nil}
  scope :within_parent, ->(parent_id){where parent_id: parent_id}
  scope :by_product_id, ->(product_id){where product_id: product_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]
  attr_writer :login
  attr_writer :ignore_valid_pass

  has_many :orders
  has_many :rates
  has_many :comments
  belongs_to :role

  enum gender: {female: 0, male: 1, other: 2}

  validates :name, :email, :phone, :address, presence: true
  validates :password, presence: true if :ignore_valid_pass.nil?

  scope :by_id, ->(id){where id: id} 

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i(create destroy)
  before_action :load_product, only: %i(new create edit update destroy)
  before_action :load_comment, only: %i(edit update destroy)

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build comment_params
    if @comment.save
      @comments = @product.comments.without_parent.infor_comment.created_desc
      flash.now[:success] = t ".create_success"

      respond_to do |format|
        format.js
      end
    else
      flash.now[:danger] = t ".blank_content"
      render :new
    end
    mention_users
	end

  def edit
  end

  def update
    if @comment.update_attributes comment_params
      flash.now[:success] = t ".update_success"
      @comments = @product.comments.without_parent.infor_comment.created_desc
      respond_to do |format|
        format.js
      end
    else
      flash.now[:danger] = t ".blank_content"
      render :edit
    end
    mention_users
  end

  def destroy
    if @comment.destroy
      flash.now[:success] = t ".delete_success"
    end
    @comments = @product.comments.without_parent.infor_comment.created_desc
    respond_to do |format|
      format.js
    end
    mention_users
  end

  def comment_params
    params.require(:comment).permit :parent_id, :product_id, :content
  end

  def load_product
    @product = Product.find_by id: params[:product_id]
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
  end

  def mention_users
    user_ids = @product.comments.pluck(:user_id).uniq
    @mention_usernames = User.by_id(user_ids).pluck(:name).join(',')
    @comment_ids = @product.comments.pluck(:id).join(',')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def check_user_comment user_id
    return true if user_id == current_user.id || current_user.role.id == 1
  end

  def replies comment
  	Comment.within_parent(comment.id).created_desc.infor_comment
  end

  def count_comment product
  	Comment.by_product_id(product.id).count
  end
end

app/views/comments/_comment.html.erb
<li class="comment">
  <div class="comment-wrap">
    <div class="comment-img">
      <img alt='' src='http://placehold.it/100x100' height='80' width='80' />
      </div>
    <article class="comment-block">
      <header class="comment-header">
        <cite class="comment-author">
          <h4><%= comment.user.name %></h4>
        </cite>
      </header>
      <div class="comment-content-<%= comment.id %>">
        <p><%= comment.content %></p>
      </div>
      <span class="comment-reply">
        <% if user_signed_in? && check_user_comment(comment.user.id) %>
          <%= link_to t(".edit"), edit_product_comment_path(@product, comment.id), remote: true, class: "comment-reply-link" %> - 
          <%= link_to t(".delete"), "javascript:;", class: "remove-comment", data: {product_id: @product.id, comment_id: comment.id} %> - 
        <% elsif user_signed_in? %>
          <%= link_to t(".reply"), "javascript:;", class: "reply-comment", class: "reply-comment", data: {parent_id: comment.id} %> - 
        <% end %>
        <%= distance_of_time_in_words(Time.now - comment.created_at) %>
      </span>
    </article>
  </div>
  <%= render partial: "comments/replies", collection: replies(comment), as: :reply, locals: {parent_id: comment.id} %>
</li>

app/views/comments/_form.html.erb
<%= simple_form_for comment, url: url, remote: true, class: "comment-form" do |form| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="comment-form-comment">
        <%= form.hidden_field :parent_id %>
        <%= form.hidden_field :product_id, value: @product.id %>
        <%= form.text_area :content, class: "form-control", id: "content", placeholder: t(".enter_comment"), cols: 40, rows: 6 %>
      </div>
    </div>
  </div>
  <div class="form-submit">
    <%= form.submit t(".submit"), id: "submit" %>
  </div>
<% end %>

app/views/comments/_replies.html.erb
<ol class="children">
  <li class="comment">
    <div class="comment-wrap">
      <div class="comment-img">
        <img alt='' src='http://placehold.it/100x100' height='80' width='80' />
        </div>
      <article class="comment-block">
        <header class="comment-header">
          <cite class="comment-author">
            <h4><%= reply.user.name %></h4>
          </cite>
        </header>
        <div class="comment-content-<%= reply.id %>">
          <p><%= reply.content %></p>
        </div>
        <span class="comment-reply">
          <% if user_signed_in? && check_user_comment(reply.user.id) %>
            <%= link_to t(".edit"), edit_product_comment_path(@product, reply.id), remote: true, class: "comment-reply-link" %> - 
            <%= link_to t(".delete"), "javascript:;", class: "remove-comment", data: {product_id: @product.id, comment_id: reply.id} %> - 
          <% elsif user_signed_in? %>
            <%= link_to t(".reply"), "javascript:;", class: "reply-comment", class: "reply-comment", data: {parent_id: parent_id} %> - 
          <% end %>
          <%= distance_of_time_in_words(Time.now - reply.created_at) %>
        </span>
      </article>
    </div>
  </li>
</ol>

app/views/comments/create.js.erb
$('.comments-title').html('<%= j count_comment(@product).to_s %>');
$('.comments-list').html('<%= j render partial: "comments/comment", collection: @comments, as: :comment %>');
$('#comment-form').html('<%= j render "comments/form", comment: Comment.new, url: product_comments_path(@product) %>');

// Mention user
var comment_ids = '<%= j @comment_ids.to_s %>';
var mention_usernames = '<%= j @mention_usernames.to_s %>';
comment_ids = comment_ids.split(',');
for(index = 0; index < comment_ids.length; index++){
  mention_user(comment_ids[index], mention_usernames);
}

$('#alert-notification').html('');
<% if flash[:danger] %>
  $('#alert-notification').addClass('alert-danger');
  $('#alert-notification').append('<%= j flash[:danger] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% elsif flash[:success] %>
  $('#alert-notification').addClass('alert-success');
  $('#alert-notification').append('<%= j flash[:success] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% end %>

app/views/comments/destroy.js.erb
$('.comments-title').html('<%= j count_comment(@product).to_s %>');
$('.comments-list').html('<%= j render partial: "comments/comment", collection: @comments, as: :comment %>');

// Mention user
var comment_ids = '<%= j @comment_ids.to_s %>';
var mention_usernames = '<%= j @mention_usernames.to_s %>';
comment_ids = comment_ids.split(',');
for(index = 0; index < comment_ids.length; index++){
  mention_user(comment_ids[index], mention_usernames);
}

$('#alert-notification').html('');
<% if flash[:success] %>
  $('#alert-notification').addClass('alert-success');
  $('#alert-notification').append('<%= j flash[:success] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% else %>
  $('#alert-notification').addClass('alert-danger');
  $('#alert-notification').append('<%= j flash[:danger] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% end %>

app/views/comments/edit.js.erb
$('#comment-form').html('<%= j render "comments/form", comment: @comment, url: product_comment_path(@product, @comment) %>')

$('#alert-notification').html('');
<% if flash[:danger] %>
  $('#alert-notification').addClass('alert-danger');
  $('#alert-notification').append('<%= j flash[:danger] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% elsif flash[:success] %>
  $('#alert-notification').addClass('alert-success');
  $('#alert-notification').append('<%= j flash[:success] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% end %>

app/views/comments/new.js.erb
$('#comment-form').html('<%= j render "comments/form", comment: @comment, url: product_comments_path(@product) %>')

$('#alert-notification').html('');
<% if flash[:danger] %>
  $('#alert-notification').addClass('alert-danger');
  $('#alert-notification').append('<%= j flash[:danger] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% elsif flash[:success] %>
  $('#alert-notification').addClass('alert-success');
  $('#alert-notification').append('<%= j flash[:success] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% end %>

app/views/comments/update.js.erb
$('.comments-title').html('<%= j count_comment(@product).to_s %> Comments');
$('.comments-list').html('<%= j render partial: "comments/comment", collection: @comments, as: :comment %>');
$('#content').val('');

// Mention user
var comment_ids = '<%= j @comment_ids.to_s %>';
var mention_usernames = '<%= j @mention_usernames.to_s %>';
comment_ids = comment_ids.split(',');
for(index = 0; index < comment_ids.length; index++){
  mention_user(comment_ids[index], mention_usernames);
}

$('#alert-notification').html('');
<% if flash[:danger] %>
  $('#alert-notification').addClass('alert-danger');
  $('#alert-notification').append('<%= j flash[:danger] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% elsif flash[:success] %>
  $('#alert-notification').addClass('alert-success');
  $('#alert-notification').append('<%= j flash[:success] %>');
  $('#alert-notification').show();
  $('#alert-notification').fadeOut(7000);
<% end %>