config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  post "languages/set_language", to: "languages#set_language"
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :booking_carts
  resources :users
  get "update_info_user", to: "booking_carts#update_info_user"
  post "order", to: "booking_carts#order"
  resources :orders, only: [:index, :new, :create, :update] do
    resources :order_details, only: [:index]
  end
  resources :order_details, only: [:update]
  resources :statisticals, only: [:create]
  
  namespace :admin do
    root "statisticals#index"
    resources :statisticals, only: [:index]
    resources :users
    resources :products
    resources :orders, only: [:index, :update] do
      resources :order_details, only: [:index]
    end
    get "report", to: "order_details#report"
    resources :order_details, only: [:index, :report]
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  enum status: {inprogress: 0, indelivery: 1, success: 2, cancel: 3}
  scope :by_order_id, ->order_id {where "order_id = ? and status <> 3", order_id}
end

app/controllers/admin/order_details_controller.rb
module Admin
  class OrderDetailsController < AdminBaseController
    before_action :load_order, only: [:index]

    def index
      @order_details = @order.OrderDetails.all
      sum = 0
      @order_details.each{|item| sum += item.quantity unless item.status == "cancel"}
      @total_quantity = sum
      sum = 0
      @order_details.each{|item| sum += item.sale_price unless item.status == "cancel"}
      @total_sale_price = sum
      
      respond_to do |format|
        format.html
        format.js
        format.pdf do
          render pdf: "invoice",
          page_size: 'A4',
          template: "admin/order_details/index.html.erb",
          layout: "admin/layouts/pdf.html",
          orientation: "Landscape",
          lowquality: true,
          zoom: 1,
          dpi: 75
        end
      end
    end

    def report
      orders = Order.all
      @order_details = []
      orders.each do |order|
        order.OrderDetails.all.each do |o|
          if o.status == "success"
            o.created_at = order.order_date
            @order_details.push(o)
          end
        end
      end

      total_quantity = 0
      total_sale_price = 0

      @order_details.each do |item| 
        total_quantity += item.quantity
        total_sale_price += item.sale_price
      end
      @total_quantity = total_quantity
      @total_sale_price = total_sale_price
    end

    private

    def load_order
      @order = Order.find_by id: params[:order_id]
      return if @order
      redirect_to root_path
    end
  end
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :load_order, only: [:index, :update]
  before_action :load_order_detail, only: [:update]

  def index
    load_order_details
  end

  def update
    if @order_detail.update_attributes status: "cancel"
      load_order_details
      update_order
      update_product_quantities
      @orders = Order.by_user_id current_user.id
      flash.now[:success] = t ".update_success"
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path
    end
  end

  private

  def load_order_details
    @order_details = @order.OrderDetails.all
    @order_user = User.find_by id: @order.user_id
    sum = 0
    @order_details.each{|item| sum += item.quantity unless item.status == "cancel"}
    @total_quantity = sum
    sum = 0
    @order_details.each{|item| sum += item.sale_price unless item.status == "cancel"}
    @total_sale_price = sum
  end

  def load_order
    @order = Order.find_by id: params[:order_id]
    return if @order
    redirect_to root_path
  end

  def load_order_detail
    @order_detail = OrderDetail.find_by id: params[:id]
    return if @order_detail && @order_detail.status == "inprogress"
    redirect_to root_path
  end

  def update_order
    check = 0
    @order_details.pluck(:status).each do |status|
      if status == "cancel"
        check += 1
      end
    end
    if check == @order_details.length
      @order.update_attributes status: "cancel"
    end
  end

  def update_product_quantities
    product = Product.find_by id: @order_detail.product_id
    new_quantity = product.quantities + @order_detail.quantity
    product.update_columns quantities: new_quantity, status: new_quantity == 0 ? 0 : 1
    product.save
  end
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
  def check_option order_details
    check = false
    order_details.pluck(:status).each do |status|
      if status == "inprogress"
        check = true
      end
    end
    check
  end
end

app/views/admin/order_details/_index.html.erb
<div class="modal-dialog modal-lg modal-order-detail-admin" role="dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" id="modal_order_detail" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><%= t ".order_detail" %></h4>
    </div>
    <div class="modal-body">
      <div class="col-md-12">
        <h3 class="text-center"><%= t ".order_detail" %></h3>
        <div class="col-md-8">
          <div class="col-md-12">
            <%= t ".receiver_name" %>: <b><%= @order.receiver_name %></b>
          </div>
          <div class="col-md-12">
            <%= t ".phone" %>: <b><%= @order.phone %></b>
          </div>
          <div class="col-md-12">
            <%= t ".email" %>: <b><%= @order.email %></b>
          </div>
          <div class="col-md-12">
            <%= t ".receiver_address" %>: <b><%= @order.receiver_address %></b>
          </div>
        </div>
        <div class="col-md-4">
          <div class="col-md-12">
            <%= t ".total_quantity" %>: <b><%= @total_quantity %></b>
          </div>
          <div class="col-md-12">
            <%= t ".total_amount" %>: <b><%= format_money @total_sale_price %></b>
          </div>
        </div>
      </div>
      <table class="table table-striped table-advance table-hover " style="margin-top: 150px;">
        <thead>
          <tr>
            <th class="text-center col-md-1"><%= t ".code" %></th>
            <th class="text-center col-md-2"><%= t ".image" %></th>
            <th class="text-center col-md-2"><%= t ".product_name" %></th>
            <th class="text-center col-md-1"><%= t ".quantity" %></th>
            <th class="text-center col-md-2"><%= t ".unit_price" %></th>
            <th class="text-center col-md-2"><%= t ".amount" %></th>
            <th class="text-center col-md-2"><%= t ".status" %></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td class="text-center order-id"><a href="javascript:;">#<%= order_detail.product.id %></a></td>
              <td class="text-center">
                <%= link_to product_path(order_detail.product.id) do %>
                  <%= image_tag order_detail.product.image, style: "width: 60px; height: 60px;" %>
                <% end %>
              </td>
              <td><%= order_detail.product.name %></td>
              <td class="text-center"><%= order_detail.quantity %></td>
              <td class="text-center"><%= format_money order_detail.product.price %></td>
              <td class="text-center"><%= format_money order_detail.sale_price %></td>
              <td class="text-center ignore-capsule">
                <p class="capsule capsule-<%= order_detail.status %>">
                  <%= t "activerecord.attributes.order.status_list.#{order_detail.status}" %>
                </p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <%= link_to 'DOWNLOAD PDF', admin_order_order_details_path(@order.id, format: :pdf), target: :_blank,
       class: "btn btn-success", type: "button" %>
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t ".cancel" %></button>
    </div>
  </div>
</div>

app/views/admin/order_details/index.html.erb
<div class="invoice-box">
  <div class="title">Chi tiết hóa đơn</div>
  <table cellpadding="0" cellspacing="0">
    <tr class="">
      <td colspan="5">
        <table cellpadding="0" cellspacing="0" style="color: darkcyan;">
          <tr>
            <td>
              <br>
              Họ tên người nhận: <%= @order.receiver_name %> <br>
              Số điện thoại: <%= @order.phone %> <br>
              Email: <%= @order.email %> <br>
              Địa chỉ người nhận: <%= @order.receiver_address %>
            </td>
            <td class="right">
              Tổng số lượng: <%= @total_quantity %><br><br>
              Tổng tiền: <%= format_money @total_sale_price %>
          </tr>
        </table>
      </td>
    </tr>

    <tr class="heading">
      <td class="left">Mã sản phẩm</td>
      <td class="left">Tên sản phẩm</td>
      <td class="left">Số lượng</td>
      <td class="left">Đơn giá</td>
      <td class="left">Thành tiền</td>
    </tr>
    <br>
    <tbody>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td class="order-id"><a href="javascript:;">#<%= order_detail.product.id %></a></td>
          <td class="text-left"><%= order_detail.product.name %></td>
          <td class=""><%= order_detail.quantity %></td>
          <td class=""><%= format_money order_detail.product.price %></td>
          <td class=""><%= format_money order_detail.sale_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- <div class="invoice-box">
  <table cellpadding="0" cellspacing="0">
    <tr>
      <td colspan="2" class="center">
        <span>Người gửi</span>
      </td>
      <td colspan="2" class="right">
        <span>Người nhận</span>
      </td>
      <td></td>
    </tr>
  </table>
  <br><br><br>
</div> -->

app/views/admin/order_details/index.js.erb
$('#order-details').html('<%= j render "index" %>')
$('#order-details').modal('show')

app/views/admin/order_details/report.html.erb
<div class="col-lg-12 main-chart">
  <div class="col-lg-12">
    <h3 class="col-lg-11 text-left">Báo cáo sản phẩm đã bán</h3>
  </div>
  <div class="col-md-11 right">
    <b>Tổng số lượng:</b> <b><%= @total_quantity %></b>
  </div>
  <div class="col-md-11 right">
    <b>Tổng tiền:</b> <b><%= format_money @total_sale_price %></b>
  </div>
  <table class="table table-striped table-advance table-hover table-bordered">
    <hr width="100%" size="1px" style="margin-top: 70px;">
    <thead>
      <tr>
        <td class="center">Mã sản phẩm</td>
        <td class="left">Tên sản phẩm</td>
        <td class="left">Số lượng</td>
        <td class="left">Đơn giá</td>
        <td class="left">Thành tiền</td>
        <td class="center">Ngày mua</td>
      </tr>
    </thead>
    <tbody id="order-list">
      <% @order_details.each do |order_detail| %>
        <tr>
          <td class="order-id center"><a href="javascript:;">#<%= order_detail.product.id %></a></td>
          <td class="text-left"><%= order_detail.product.name %></td>
          <td class=""><%= order_detail.quantity %></td>
          <td class=""><%= format_money order_detail.product.price %></td>
          <td class=""><%= format_money order_detail.sale_price %></td>
          <td class="text-center"><%= order_detail.created_at.strftime("%B %e, %Y at %I:%M %p") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal fade" id="order-details" role="dialog"></div>
  <div class="col-md-12 pagination-product text-center">
    <%#= will_paginate @order_details %>
  </div>
</div>