config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  post "languages/set_language", to: "languages#set_language"
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :booking_carts
  resources :users
  get "update_info_user", to: "booking_carts#update_info_user"
  post "order", to: "booking_carts#order"
  resources :orders, only: [:index, :new, :create, :update] do
    resources :order_details, only: [:index]
  end
  resources :order_details, only: [:update]
  resources :statisticals, only: [:create]
  
  namespace :admin do
    root "statisticals#index"
    resources :statisticals, only: [:index]
    resources :users
    resources :products
    resources :orders, only: [:index, :update] do
      resources :order_details, only: [:index]
    end
    get "report", to: "order_details#report"
    resources :order_details, only: [:index, :report]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]
  attr_writer :login
  attr_writer :ignore_valid_pass

  has_many :orders
  has_many :rates
  has_many :comments
  belongs_to :role

  enum gender: {female: 0, male: 1, other: 2}

  validates :name, :email, :phone, :address, presence: true
  validates :password, presence: true if :ignore_valid_pass.nil?

  scope :by_id, ->(id){where id: id} 

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminBaseController
    before_action :load_user, only: %i(show edit update destroy)

    def index
      @users = User.order('id asc').page(params[:page]).per_page 8
    end

    def show; end

    def new
      @user = User.new
      respond_to do |format|
        format.js
      end
    end

    def create
      @user = User.new user_params
      if @user.save
        flash[:success] = "Them thanh cong"
        redirect_to admin_users_path
      else
        flash.now[:danger] = "Them that bai"
        respond_to do |format|
          format.js {render :new}
        end
      end
    end

    def edit; end

    def update
      if @user.update_attributes user_params
        flash[:success] = t ".update_success"
        redirect_to admin_users_path
      else
        flash.now[:danger] = t ".update_failed"
        respond_to do |format|
          format.js {render :edit}
          format.html {redirect_back fallback_location: admin_users_path}
        end
      end
    end

    def destroy
      if @user.destroy
        flash[:success] = t ".destroy_success"
      else
        flash[:danger] = t ".destroy_failed"
      end
      redirect_to admin_users_path
    end

    private

    def load_user
      @user = User.find_by id: params[:id]
      return if @user
      flash[:danger] = t "users.show.not_found"
      redirect_to root_path
    end

    def user_params
      params.require(:user).permit :name, :username, :email, :birthday, :phone, :address,
       :password, :password_confirmation, :role_id
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: %i(update)

  def edit; end

  def update
    @user.ignore_valid_pass = true
    if @user.update_attributes user_params
      flash[:success] = t ".update_success"
      redirect_to order_path
    else
      flash.now[:danger] = t ".update_failed"
      respond_to do |format|
        format.js {render 'booking_carts/update_info_user'}
      end
    end
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "users.show.not_found"
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit :name, :email, :phone, :address
  end
end

app/views/admin/users/_form.html.erb
<!-- Modal -->
<div class="modal-dialog modal-lg">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"></h4>
    </div>
    <div class="modal-body col-md-offset-2 col-md-8">
      <div class="">
        <%= simple_form_for [:admin, @user], method: type,
        html: {id: "form-validation", class: "form-horizontal"}, defaults: {input_html: {class: "form-control" }}, remote: true do |f| %>
          <div class="form-group">
            <%= f.input :name,  autofocus: true, class: "form-control", placeholder: "name..." %>
          </div>

          <div class="form-group">
            <%= f.input :username, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.input :email, class: "form-control", placeholder: "email..." %>
          </div>

          <div class="form-group">
            <%= f.label :birthday %>
            <%= f.date_field :birthday, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.input :address, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.input :phone, class: "form-control" %>
          </div>

          <div class="form-group password">
            <%= f.input :password, autocomplete: "off", class: "form-control" %>
          </div>

          <div class="form-group password">
            <%= f.input :password_confirmation, autocomplete: "off", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.hidden_field :role_id, value: 1 %>
          </div>

          <div class="actions text-center">
            <%= f.submit t(".#{action_name}"), class: "btn btn-primary submit" %>
            <%= f.button :button, t(".close"), type: "button", class: "btn btn-default", data: {dismiss: "modal"} %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="modal-footer">
    </div>
  </div>
</div>

app/views/admin/users/edit.js.erb
$(document).ready(function(){
  $('#new-user-modal').html('<%= j render "form", type: :patch %>');
  $('#new-user-modal').modal('show');
  $('.modal-title').html('<%= j t ".edit_user" %>');

  $('.error').css('color', 'red');
  $('.error').parent().find('input').css('border', '1px solid red');

  $('#alert-notification').html('');
  <% if flash[:danger] %>
    $('#alert-notification').addClass('alert-danger');
    $('#alert-notification').append('<%= j flash[:danger] %>');
    $('#alert-notification').show();
    $('#alert-notification').fadeOut(7000);
  <% elsif flash[:success] %>
    $('#alert-notification').addClass('alert-success');
    $('#alert-notification').append('<%= j flash[:success] %>');
    $('#alert-notification').show();
    $('#alert-notification').fadeOut(7000);
  <% end %>
});

app/views/admin/users/index.html.erb
<div class="col-lg-12 main-chart">
  <div class="col-lg-12">
    <h3 class="col-lg-11 text-left"><%= t ".user_list" %></h3>
    <%#= link_to "Thêm mới", new_admin_user_path, class: "btn btn-primary col-lg-1 text-right", remote: true, style: "margin-top: 15px;" %>
  </div>
  <table class="table table-striped table-advance table-hover table-bordered table-users">
    <hr width="100%" size="1px" style="margin-top: 70px;">
    <thead>
      <tr>
        <th class="text-center"><i class="fa fa-file-code-o"></i> <%= t ".code" %></th>
        <th class="text-center"><i class="fa fa-user"></i> <%= t ".name" %></th>
        <th class="text-center"><i class="fa fa-envelope"></i> <%= t ".email" %></th>
        <th class="text-center"><i class="fa fa-phone"></i> <%= t ".phone" %></th>
        <th class="text-center"><i class="fa fa-intersex"></i> <%= t ".gender" %></th>
        <th class="text-center"><i class="fa fa-user-times"></i> <%= t ".role" %></th>
        <th class="text-center"><i class="fa fa-edit"></i> <%= t ".option" %></th>
      </tr>
    </thead>
    <tbody class="user-list">
      <% @users.each do |user| %>
        <tr>
          <td class="text-center" id="user-id"><%= user.id %></td>
          <td class="text-center"><%= user.name %></td>
          <td class="hidden-phone text-center"><%= user.email %></td>
          <td class="text-center"><%= user.phone %></td>
          <td class="text-center"><%= user.gender %></td>
          <td class="text-center"><%= user.role.name %></td>
          <td class="text-center">
            <%= link_to admin_user_path(user.id), remote: true, title: t(".show"), class: "btn btn-success btn-xs" do %>
              <i class="fa fa-info-circle"></i>
            <% end %>
            <% unless user.role.name == "admin" %>
              <%= button_tag "", type: "button", data: {id: user.id}, class: "btn btn-danger btn-xs delete-user", title: t(".del") do %>
                <i class="fa fa-trash-o "></i>
              <% end %>
            <% else %>
              <%= link_to edit_admin_user_path(user.id), remote: true, title: t(".edit"), class: "btn btn-primary btn-xs" do %>
                <i class="fa fa-pencil"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="col-md-12 pagination-product text-center">
    <%= will_paginate @users %>
  </div>
  <div class="modal fade" id="new-user-modal" role="dialog"></div>
</div>

app/views/admin/users/new.js.erb
$('#new-user-modal').html('<%= j render "form", type: :post %>');
$('#new-user-modal').modal('show');

$('.error').css('color', 'red');
$('.error').parent().find('input').css('border', '1px solid red');

$('#alert-notification').html('');
<% if flash[:danger] %>
  resetAlert();
  $('#alert-notification').addClass('alert-danger');
  $('#alert-notification').append('<%= j flash[:danger] %>');
  $('#alert-notification').show();
<% elsif flash[:success] %>
  resetAlert();
  $('#alert-notification').addClass('alert-success');
  $('#alert-notification').append('<%= j flash[:success] %>');
  $('#alert-notification').show();
<% end %>

app/views/admin/users/show.js.erb
$('#new-user-modal').html('<%= j render "form", type: :post %>');
$('#new-user-modal').modal('show');
$('.modal-title').html('<%= j t ".detail_infor" %>');
$('input').prop('disabled', true);
$('.password').hide();
$('.submit').hide();