config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  post "languages/set_language", to: "languages#set_language"
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :booking_carts
  resources :users
  get "update_info_user", to: "booking_carts#update_info_user"
  post "order", to: "booking_carts#order"
  resources :orders, only: [:index, :new, :create, :update] do
    resources :order_details, only: [:index]
  end
  resources :order_details, only: [:update]
  resources :statisticals, only: [:create]
  
  namespace :admin do
    root "statisticals#index"
    resources :statisticals, only: [:index]
    resources :users
    resources :products
    resources :orders, only: [:index, :update] do
      resources :order_details, only: [:index]
    end
    get "report", to: "order_details#report"
    resources :order_details, only: [:index, :report]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :description, dependent: :destroy
  belongs_to :region
  belongs_to :category
  belongs_to :provider
  has_many :cetifications
  has_many :comments

  mount_uploader :image, ImageUploader

  attr_accessor :amount
  attr_accessor :quantity

  validates :title, :name, :image, :price, :status, :quantities, :region_id, :category_id, :provider_id, presence: true
  validates :price, inclusion: {in: 1000..10000000}
  validates :discount, inclusion: {in: 0..100}, allow_blank: true
  validates :quantities, inclusion: {in: 1..1000000}

  scope :by_region_product, -> id {where region_id: id}
  scope :by_product_id, -> id {where id: id}

  accepts_nested_attributes_for :description, allow_destroy: true
  enum status: {out_of_stock: 0, stocking: 1}
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminBaseController
    before_action :load_product, only: %i(show edit update destroy)
    skip_before_action :verify_authenticity_token, only: %i(create update)

    def index
      @products = Product.order('region_id asc').page(params[:page]).per_page 8
    end

    def show; end

    def new
      @product = Product.new
      @product.build_description
      respond_to do |format|
        format.js
      end
    end

    def create
      @product = Product.new product_params
      if @product.save
        flash[:success] = t ".create_success"
        redirect_to admin_products_path
      else
        flash[:danger] = t ".create_failed"
        respond_to do |format|
          format.js {render :new}
          format.html {redirect_back fallback_location: new_admin_product_path}
        end
      end
    end

    def edit; end

    def update
      params[:product].except(:image) if params[:product][:image].nil?
      if @product.update_attributes product_params
        flash[:success] = t ".update_success"
        redirect_to admin_products_path
      else
        flash.now[:danger] = t ".update_failed"
        respond_to do |format|
          format.js {render :edit}
          format.html {redirect_back fallback_location: admin_products_path}
        end
      end
    end

    def destroy
      if @product.destroy
        flash[:success] = t ".destroy_success"
      else
        flash[:danger] = t ".destroy_failed"
      end
      redirect_to admin_products_path
    end

    private

    def load_product
      @product = Product.find_by id: params[:id]
      return if @product
      flash[:danger] = t "users.show.not_found"
      redirect_to root_path
    end

    def product_params
      params[:product][:status] = 1
      params.require(:product).permit :title, :name, :image, :price, :discount, :status,
        :quantities, :region_id, :category_id, :provider_id, description_attributes: :content
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_products, only: %i(show)

  def index
    query = params[:query]
    if !query.nil? && query.strip! != ""
      @products = Product.where("name LIKE :name", name: "#{query}%").order('region_id asc').page(params[:page]).per_page 4
      respond_to do |format|
        format.js
      end
    else
      @products = Product.order('region_id asc').page(params[:page]).per_page 4
    end
    most_bought_product
  end

  def show
    @comment = Comment.new
    @comments = @product.comments.without_parent.infor_comment.created_desc

    user_ids = @product.comments.pluck(:user_id).uniq
    @mention_usernames = User.by_id(user_ids).pluck(:name).join(',')

    gon.comment_ids = @product.comments.pluck(:id)
    gon.mention_usernames = @mention_usernames

    most_bought_product
  end

  private

  def load_products
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  def most_bought_product
    most_bought = OrderDetail.limit(6).pluck(:product_id)
    most_bought = most_bought + Product.limit(6 - most_bought.length).pluck(:id) if most_bought.length < 6
    @most_bought_products = Product.where(id: most_bought)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def collection_name model
    model.all.map{|value| [value.name, value.id]}
  end

  def selected object
    return object.id unless object.nil?
    return 1
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def set_number_product product
    if session[:cart].nil? || session[:cart].empty?
      return 1
    else
      index_product = session[:cart].find_index(product)
      if index_product.nil?
        return 1
      else
        return session[:cart][index_product].quantity.to_i
      end
    end
  end

  def check_disable product
    product.status == "out_of_stock" ? true : false
  end
end

app/views/products/_product.html.erb
<div class="masonry-item noo-product-column col-md-4 col-sm-6 product">
  <div class="noo-product-inner">
    <div class="noo-product-thumbnail">
      <%= link_to product_path(product.id) do %>
        <%= image_tag product.image, style: "width: 600; height: 760;" %>
      <% end %>
      <div class="noo-rating">
        <div class="star-rating">
          <span style="width:0%"></span>
        </div>
      </div>
    </div>
    <div class="noo-product-title">
      <h3><%= link_to product.name, product_path(product.id) %></h3>
      <span class="price"><span class="amount"><%= format_money product.price %></span></span>
      <div class="noo-product-excerpt">
        <p><%= product.description.content %></p>
      </div>
      <div class="noo-product-action">
        <div class="noo-action">
          <%= link_to product_path(product.id), class: "button product_type_simple add_to_cart_button" do %>
            <span><%= t ".bought_now" %></span>
          <% end %>
          <div class="yith-wcwl-add-to-wishlist">
            <div class="yith-wcwl-add-button">
              <a href="javascript:;" class="add_to_wishlist"></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_list.html.erb
<div class="noo-catalog">
  <%# <p class="commerce-result-count">Showing 1&ndash;9 of 18 results</p> %>
  <!-- <form class="commerce-ordering pull-right">
    <select name="orderby" class="orderby">
      <option value="" selected='selected'><%= t ".order" %></option>
      <option value=""><%= t ".order_by_price" %></option>
      <option value=""><%= t ".order_by_name" %></option>
    </select>
  </form> -->
  <%# <div class="product-style-control pull-left">
      <span class="noo-list active"><i class="fa fa-th-list"></i></span>
      <span class="noo-grid"><a href="#"><i class="fa fa-th-large"></i></a></span>
  </div> %>
</div>
<div class="products row product-list">
  <% @products.each do |product| %>
    <%= render product %>
  <% end %>
</div>
<div class="col-md-12 pagination-product text-center">
  <%= will_paginate @orders %>
</div>

app/views/products/_quantity.html.erb
<%= hidden_field_tag "id", @product.id %>
<%= number_field_tag "quantity", set_number_product(@product), min: 1, max: 100, class: "text-center" %>

app/views/products/index.html.erb
<section class="noo-page-heading eff">
  <div class="container">
    <div class="noo-heading-content">
      <h1 class="page-title eff"><%= t ".product_list" %></h1>
      <div class="noo-page-breadcrumb eff">
        <a href="index.html" class="home"><%= t ".specialty_three_regions" %></a>/<span><%= t ".product" %></span>
      </div>
    </div>
  </div>
</section>
<div class="main">
  <div class="commerce noo-shop-main">
    <div class="container">
      <div class="row">
        <div class="noo-main col-md-9" id="products">
          <%= render partial: "product_list", locals: { products: @products } %>
        </div>
        <div class="noo-sidebar col-md-3">
          <div class="noo-sidebar-wrap">
            <div class="widget commerce widget_product_search">
              <h3 class="widget-title"><%= t ".search" %></h3>
              <%= form_with url: "/products", method: :get, class: "form-search" do |form| %>
                <%= form.text_field :query, placeholder: "Tìm kiếm", class: "form-search" %>
                <%= form.submit "search", id: "submit" %>
              <% end %>
            </div>
            <div class="widget commerce widget_product_categories">
              <h3 class="widget-title"><%= t ".region" %></h3>
              <ul class="product-categories">
                <li><a href="#"><%= t ".north" %></a></li>
                <li><a href="#"><%= t ".central" %></a></li>
                <li><a href="#"><%= t ".south" %></a></li>
              </ul>
            </div>
            <div class="widget commerce widget_products">
              <h3 class="widget-title"><%= t ".most_bought" %></h3>
              <ul class="product_list_widget">
                <% @most_bought_products.each do |product| %>
                  <li>
                    <%= link_to product_path(product.id) do %>
                      <%= image_tag product.image, style: "width: 100; height: 100;" %>
                      <span class="product-title"><%= product.name %></span>
                    <% end %>
                    <span class="amount"><%= format_money product.price %></span>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.js.erb
$('#products').html('<%= j render partial: "product_list", locals: { products: @products } %>');

app/views/products/show.html.erb
<section class="noo-page-heading eff heading-6">
  <div class="container">
    <div class="noo-heading-content">
      <h1 class="page-title eff"><%= t ".product_detail" %></h1>
      <div class="noo-page-breadcrumb eff">
        <%= link_to t(".specialty_three_regions"), products_path, class: "home" %>
        <span>/ <%= t ".detail" %></span>
      </div>
    </div>
  </div>
</section>
<div class="main">
  <div class="commerce single-product noo-shop-main">
    <div class="container">
      <div class="row">
        <div class="noo-main col-md-9">
          <div class="product">
            <div class="single-inner">
              <div class="images">
                <div class="product-simple-image">
                  <%= image_tag @product.image, style: "width: 300; height: 381" %>
                </div>
              </div>
              <div class="summary entry-summary">
                <h1 class="product_title entry-title"><%= @product.name %></h1>
                <p class="price"><span class="amount"><%= format_money @product.price %></span></p>
                <p class="description"><%= @product.description.content %></p>
                <div class="product_meta">
                  <span class="posted_in">Vị trí: <%= @product.region.name %></span>
                </div>
                <%= form_tag "/booking_carts", method: :post, remote: true, class: "cart" do %>
                  <div class="quantity">
                    <%= render "quantity" %>
                  </div>
                  <%= submit_tag t(".add_to_cart"), class: "single_add_to_cart_button button", disabled: check_disable(@product) %>
                <% end %>
                <input class="single_add_to_cart_button button product-<%= @product.status %>" type="reset" style="width: -1px; margin-left: 10px;" value='<%= t ".#{@product.status}" %>' />
                <!-- <div class="yith-wcwl-add-to-wishlist">
                  <div class="yith-wcwl-add-button">
                    <a href="#" class="add_to_wishlist"></a>
                  </div>
                </div> -->
            
                <div class="clear"></div>
                <div class="noo-social-share">
                  <span><%= t ".share" %>:</span>
                  <a href="#share" class="noo-share" title="Share on Facebook">
                    <i class="fa fa-facebook"></i>
                  </a>
                  <a href="#share" class="noo-share" title="Share on Twitter">
                    <i class="fa fa-twitter"></i>
                  </a>
                  <a href="#share" class="noo-share" title="Share on Google+">
                    <i class="fa fa-google-plus"></i>
                  </a>
                  <a href="#share" class="noo-share" title="Share on Pinterest">
                    <i class="fa fa-pinterest"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="commerce-tabs">
              <ul class="nav nav-tabs tabs">
                <li class="active">
                  <a data-toggle="tab" href="#tab-1"><%= t ".detail" %></a>
                </li>
                <li>
                  <a data-toggle="tab" href="#tab-2"><%= t ".reviews" %></a>
                </li>
              </ul>
              <div class="tab-content">
                <div id="tab-1" class="tab-pane fade in active">
                  <p><%= @product.description.content %></p>
                  <p>Thành phần: <%= @product.description.ingredient %></p>
                </div>
                <div id="tab-2" class="tab-pane fade">
                  <div id="comment-content">
                    <div id="comments" class="comments-area">
                      <h2 class="comments-title col-md-1 text-center"><%= count_comment @product %></h2><h2 class="col-md-11"><%= t ".reviews" %></h2>
                      <ol class="comments-list">
                        <%= render partial: "comments/comment", collection: @comments, as: :comment %>
                      </ol>
                    </div>
                  </div>
                  <div id="respond-wrap">
                    <div id="respond" class="comment-respond">
                      <h3 id="reply-title" class="comment-reply-title">
                        <span><%= t ".thought" %></span>
                      </h3>
                      <% if user_signed_in? %>
                        <div id="comment-form">
                          <%= render "comments/form", comment: @comment, url: product_comments_path(@product) %>
                        </div>
                      <% else %>
                        <%= t ".request_comment1" %><%= link_to t(".login"), new_user_session_path %><%= t ".request_comment2" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="related products">
              <h2><%= t ".product_relate" %></h2>
              <div class="products row product-grid">
                <% region_porduct(@product.region.id).limit(3).each do |product| %>
                  <div class="masonry-item noo-product-column col-md-4 col-sm-6 product">
                    <div class="noo-product-inner">
                      <div class="noo-product-thumbnail">
                        <%= link_to product_path(product.id) do %>
                          <%= image_tag product.image, style: "width: 600; height: 760" %>
                        <% end %>
                        <div class="noo-rating">
                          <div class="star-rating">
                            <span style="width:20%"></span>
                          </div>
                        </div>
                      </div>
                      <div class="noo-product-title">
                        <h3><%= link_to product.name, product_path(product.id) %></h3>
                        <span class="price"><span class="amount"><%= format_money product.price %></span></span>
                        <div class="noo-product-action">
                          <div class="noo-action">
                            <%= link_to "#", class: "button product_type_simple add_to_cart_button" do %>
                              <span><%= t ".add_to_cart" %></span>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="noo-sidebar col-md-3">
          <div class="noo-sidebar-wrap">
            <div class="widget commerce widget_products">
              <h3 class="widget-title"><%= t ".most_bought" %></h3>
              <ul class="product_list_widget">
                <% @most_bought_products.each do |product| %>
                  <li>
                    <%= link_to product_path(product.id) do %>
                      <%= image_tag product.image %>
                      <span class="product-title"><%= product.title %></span>
                    <% end %>
                    <span class="amount"><%= format_money product.price %></span>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>